name: NoGrief
version: "$version"
main: me.elephant1214.nogrief.NoGrief
author: Elephant_1214
api-version: "1.20"
loader: me.elephant1214.nogrief.bootstrap.NoGriefLoader
bootstrapper: me.elephant1214.nogrief.bootstrap.NoGriefBootstrap
dependencies:
  server:
    Pl3xMap:
      load: BEFORE
      required: false
      join-classpath: true
